kind: pipeline
trigger:
  event:
    - cron
    - push
    - tag
  branch:
    - master

environment:
  BASE_REPO_API: https://api.github.com/repos/cenk1cenk2/softether-vpncli/releases/latest
  TRACK_REPO_API: https://api.github.com/repos/SoftEtherVPN/SoftEtherVPN/releases/latest

name: auto-deploy
steps:
  - name: check-version
    image: alpine/git:latest
    commands:
      - apk add curl --no-cache --no-progress
      - export BASE_RELEASE=$(curl --silent $BASE_REPO_API | grep "tag_name" | sed -r 's/.*(".*").*"(.*)".*/\2/g')
      - export TRACK_RELEASE=$(curl --silent $TRACK_REPO_API | grep "tag_name" | sed -r 's/.*(".*").*"(.*)".*/\2/g')
      - 'echo "Repository last tag: $BASE_RELEASE"'
      - 'echo "Tracking last tag: v$TRACK_RELEASE"'
      - git config --global --add url."https://$GITHUB_USERNAME:$GITHUB_DEPLOY_TOKEN@github.com/".insteadOf "https://github.com/"
      - 'if [ "$BASE_RELEASE" != "v$TRACK_RELEASE" ]; then sed -ri "s/.*(version:.*\| v)(.*),.*/\1$TRACK_RELEASE, $(date ''+%Y%m%d'') \| Autoupdated/" README.md && git add . && git commit -m "Autoupdated to version v$TRACK_RELEASE@$(date ''+%Y%m%d'')." && git push -u origin master && git tag v$TRACK_RELEASE && git push origin v$TRACK_RELEASE || echo "No new version has been found."; fi'
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_DEPLOY_TOKEN:
        from_secret: github_deploy_token
    when:
      event:
        - cron
        - push
      branch:
        - master

  - name: publish
    image: plugins/docker
    working_dir: /drone/src/build
    settings:
      repo: cenk1cenk2/softether-vpncli
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tag:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag
      branch:
        - master
