kind: pipeline
trigger:
  event:
    - cron
    - push
    - tag
  branch:
    - master

name: auto-deploy
steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      semantic_release: false
      update_readme_toc: true
      readme_location: README.md
      git_method: gh
      git_user_name: semantic-relase
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_deploy_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_hub_username
      docker_password:
        from_secret: docker_hub_password
      docker_repo: cenk1cenk2/softether-vpncli
    when:
      event:
        - cron
        - push
      branch:
        - master

  - name: track-repository
    image: cenk1cenk2/drone-track-repository
    settings:
      this_repo: cenk1cenk2/softether-vpncli
      track_repo: SoftEtherVPN/SoftEtherVPN
      git_username:
        from_secrets: github_username
      git_token:
        from_secrets: github_deploy_token
      do_tag: true
      do_release: true
    when:
      event:
        - cron
        - push
      branch:
        - master

  - name: publish
    image: plugins/docker
    working_dir: /drone/src/build
    settings:
      repo: cenk1cenk2/softether-vpncli
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tag:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag
      branch:
        - master
