version: '3'
services:
  softether-vpncli:
    image: softether-vpncli
    build: ./build/.
    container_name: softether-vpncli
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    restart: "no"
    volumes:
      # vpn client config
      - ./${CONNNAME}.vpn:/${CONNNAME}.vpn
      # samba share paths if samba enabled
    network_mode: "host"
    # Add this if you want to connect your host computer if Linux to VPN or just the container
    cap_add: 
      - NET_ADMIN