version: '3'
services:
  softether-vpncli:
    image: softether-vpncli
    build: ./build/.
    container_name: softether-vpncli
    env_file: .env
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    restart: "no"
    volumes:
      # vpn client config
      - ./${CONNNAME}.vpn:/s6-bin/softether-vpncli/${CONNNAME}.vpn
    privileged: true
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
