version: '3'
services:
  softether-vpncli-int:
    image: softether-vpncli-int
    build: ./build/.
    container_name: softether-vpncli-int
    env_file: .env
    restart: "no"
    volumes:
      # vpn client config
      - ./${CONNNAME}.vpn:/s6-bin/softether-vpncli/${CONNNAME}.vpn
    privileged: true
    network_mode: "host"
