## Refer to the GitHub repository for configuration and problems.
## Cenk Kilic <cenk@kilic.dev>
## https://srcs.kilic.dev/softether-vpncli
version: '3'
services:
  softether-vpncli:
    image: cenk1cenk2/softether-vpncli
    container_name: softether-vpncli
    env_file: .env
    restart: "no"
    volumes:
      # vpn client config
      - ./${CONNNAME}.vpn:/${CONNNAME}.vpn
      # samba share paths if samba enabled
    # ports:
      # - 139:139
      # - 445:445
    # Set this to host if you want to connect your host computer if Linux to VPN or just the container, else bridge
    network_mode: "host"
    # Add this if you want to connect your host computer if Linux to VPN or just the container
    privileged: true
